<a href="https://colab.research.google.com/github/mansooraha/scikit-learn/blob/main/pandasNA_encoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# ✅ Create a DataFrame with pandas.NA
df = pd.DataFrame({
    "color": pd.Series(["Red", "Blue", pd.NA, "Green"], dtype="string")
})

print("Original DataFrame with pd.NA:")
print(df)

#  Attempting default OneHotEncoder causes error
try:
    encoder = OneHotEncoder(sparse_output=False)
    encoder.fit_transform(df)
except Exception as e:
    print("\n Default encoder failed with error:")
    print(e)

# ✅ Workaround: Replace pd.NA with a placeholder
df_filled = df.fillna("__PANDAS_NA__")
encoder = OneHotEncoder(sparse_output=False, handle_unknown="ignore")
encoded = encoder.fit_transform(df_filled)

print("\n✅ Encoded output with pd.NA treated as category:")
print(encoded)
print("\nFeature names:", encoder.get_feature_names_out())


Original DataFrame with pd.NA:
   color
0    Red
1   Blue
2   <NA>
3  Green

 Default encoder failed with error:
Encoders require their input argument must be uniformly strings or numbers. Got ['NAType', 'str']

✅ Encoded output with pd.NA treated as category:
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]

Feature names: ['color_Blue' 'color_Green' 'color_Red' 'color___PANDAS_NA__']
